# Generated by Django 5.2.1 on 2025-05-31 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_favorite_genre_favorite_runtime_minutes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
