# Generated by Django 5.2.1 on 2025-05-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='overview',
        ),
    ]
