# Generated by Django 5.2.1 on 2025-06-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='archive_identifier',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
