# Generated by Django 5.2.1 on 2025-06-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_public_domain',
            field=models.BooleanField(default=False),
        ),
    ]
