# Generated by Django 5.2.1 on 2025-06-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_is_public_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_public_domain',
            field=models.BooleanField(default=True),
        ),
    ]
