# Generated by Django 5.2.1 on 2025-06-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movie_is_public_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
