# Generated by Django 5.2.1 on 2025-06-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_is_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='archive_identifier',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=350, unique=True),
        ),
    ]
