# Generated by Django 5.2.1 on 2025-06-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_movie_archive_identifier_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='archive_identifier',
            field=models.CharField(max_length=600, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
