# Generated by Django 5.2.1 on 2025-06-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
